"use client";

import { Copy, RefreshCw, RotateCcw } from "lucide-react";
import { useCallback, useEffect, useMemo, useState } from "react";
import { Button } from "../components/ui/button";
import { Card, CardContent, CardHeader } from "../components/ui/card";
import { EmptyState } from "../components/ui/empty-state";
import { LoadingSkeleton } from "../components/ui/loading-skeleton";
import { StatusBadge } from "../components/ui/status-badge";
import {
  listDemoSeedProfiles,
  runDemoSeedProfile,
  type DemoSeedProfileRead,
  type DemoSeedResult,
  type VendorAccessCreatedResponse
} from "./frontend-api";

const CONFIRM_TEXT = "SEED_DEMO_PROFILE";

export function DemoSeedAdminPanel({
  accessToken,
  apiBaseUrl,
  canAdmin,
  tenantId
}: {
  accessToken: string | null;
  apiBaseUrl: string | null;
  canAdmin: boolean;
  tenantId: string | null;
}) {
  const [profiles, setProfiles] = useState<DemoSeedProfileRead[]>([]);
  const [selectedProfile, setSelectedProfile] = useState<string>("analytics_rich_demo");
  const [confirmText, setConfirmText] = useState("");
  const [result, setResult] = useState<DemoSeedResult | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [isSeeding, setIsSeeding] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const loadProfiles = useCallback(async () => {
    if (!apiBaseUrl || !accessToken || !canAdmin) return;
    setIsLoading(true);
    setError(null);
    try {
      const loaded = await listDemoSeedProfiles(apiBaseUrl, accessToken);
      setProfiles(loaded);
      if (loaded.length && !loaded.some((profile) => profile.key === selectedProfile)) {
        setSelectedProfile(loaded[0].key);
      }
    } catch (loadError) {
      setError(loadError instanceof Error ? loadError.message : "Demo seed profiles could not be loaded.");
    } finally {
      setIsLoading(false);
    }
  }, [accessToken, apiBaseUrl, canAdmin, selectedProfile]);

  useEffect(() => {
    void loadProfiles();
  }, [loadProfiles]);

  const selected = useMemo(
    () => profiles.find((profile) => profile.key === selectedProfile) ?? profiles[0],
    [profiles, selectedProfile]
  );

  const canRun = Boolean(apiBaseUrl && accessToken && tenantId && canAdmin && selected?.key && confirmText === CONFIRM_TEXT);

  async function runSeed() {
    if (!apiBaseUrl || !accessToken || !tenantId || !selected?.key) return;
    setIsSeeding(true);
    setError(null);
    setResult(null);
    try {
      const seeded = await runDemoSeedProfile(apiBaseUrl, accessToken, tenantId, selected.key, confirmText);
      setResult(seeded);
      setConfirmText("");
    } catch (seedError) {
      setError(seedError instanceof Error ? seedError.message : "Demo seed profile could not run.");
    } finally {
      setIsSeeding(false);
    }
  }

  return (
    <section className="scroll-mt-6 space-y-4" id="demo-seed-profiles">
      <div className="flex flex-col gap-3 lg:flex-row lg:items-end lg:justify-between">
        <div>
          <h2 className="text-lg font-semibold">Demo Seed Profiles</h2>
          <p className="mt-1 text-sm text-muted">
            Reset the current demo tenant into a known profile for repeatable demos and QA. Use only on private staging/demo environments.
          </p>
        </div>
        <Button disabled={!canAdmin || isLoading} onClick={() => void loadProfiles()} variant="secondary">
          <RefreshCw className="h-4 w-4" />
          Reload profiles
        </Button>
      </div>

      {!canAdmin ? (
        <EmptyState
          description="Only tenant admins can reset seed data because the operation replaces demo workflow history for the current tenant."
          title="Demo seeding is admin-only"
        />
      ) : (
        <Card>
          <CardHeader className="space-y-2">
            <div className="flex flex-col gap-3 lg:flex-row lg:items-start lg:justify-between">
              <div>
                <h3 className="text-base font-semibold">Controlled tenant reset</h3>
                <p className="mt-1 text-sm text-muted">
                  Seeding is tenant-scoped, requires <span className="font-mono">{CONFIRM_TEXT}</span>, and is blocked by backend production guardrails.
                </p>
              </div>
              <StatusBadge status="destructive" />
            </div>
            <div className="rounded-md border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-900">
              This resets demo data for the current tenant. Vendor tokens generated by a profile are shown only once.
            </div>
          </CardHeader>
          <CardContent className="space-y-5">
            {error ? <div className="rounded-md border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-800">{error}</div> : null}

            {isLoading && !profiles.length ? (
              <div className="grid gap-3 lg:grid-cols-3">
                {[0, 1, 2].map((item) => <LoadingSkeleton className="h-44 w-full" key={item} />)}
              </div>
            ) : profiles.length ? (
              <>
                <div className="grid gap-3 lg:grid-cols-2 xl:grid-cols-3">
                  {profiles.map((profile) => (
                    <button
                      className={`rounded-md border p-4 text-left transition ${
                        selected?.key === profile.key ? "border-primary bg-primary/5" : "border-border bg-surface hover:bg-slate-50"
                      }`}
                      key={profile.key}
                      onClick={() => setSelectedProfile(profile.key)}
                      type="button"
                    >
                      <div className="flex items-start justify-between gap-3">
                        <div>
                          <h4 className="font-semibold">{profile.label}</h4>
                          <p className="mt-1 text-sm text-muted">{profile.description}</p>
                        </div>
                        {selected?.key === profile.key ? <StatusBadge status="selected" /> : null}
                      </div>
                      <p className="mt-3 text-xs text-muted">Recommended for: {profile.recommended_for}</p>
                      <ul className="mt-3 space-y-1 text-xs text-muted">
                        {profile.includes.slice(0, 4).map((item) => (
                          <li key={item}>- {item}</li>
                        ))}
                      </ul>
                    </button>
                  ))}
                </div>

                <div className="grid gap-4 lg:grid-cols-[minmax(0,1fr)_auto] lg:items-end">
                  <label className="space-y-2 text-sm">
                    <span className="font-medium">Confirmation</span>
                    <input
                      className="w-full rounded-md border border-border bg-surface px-3 py-2 text-sm"
                      onChange={(event) => setConfirmText(event.target.value)}
                      placeholder={CONFIRM_TEXT}
                      value={confirmText}
                    />
                    <span className="block text-xs text-muted">
                      Type <span className="font-mono">{CONFIRM_TEXT}</span> to enable the seed action.
                    </span>
                  </label>
                  <Button disabled={!canRun || isSeeding} onClick={() => void runSeed()} variant="danger">
                    <RotateCcw className="h-4 w-4" />
                    {isSeeding ? "Seeding..." : `Run ${selected?.label ?? "seed profile"}`}
                  </Button>
                </div>
              </>
            ) : (
              <EmptyState
                description="Seed profile metadata will appear here when the API is available and this user has tenant admin permission."
                title="No seed profiles loaded"
              />
            )}

            {result ? <SeedResult result={result} /> : null}
          </CardContent>
        </Card>
      )}
    </section>
  );
}

function SeedResult({ result }: { result: DemoSeedResult }) {
  return (
    <div className="space-y-4 rounded-md border border-border bg-surface p-4">
      <div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
        <div>
          <h4 className="font-semibold">{result.message}</h4>
          <p className="mt-1 text-sm text-muted">Profile: {result.profile_key}</p>
        </div>
        <StatusBadge status={result.status} />
      </div>

      <div className="grid gap-3 lg:grid-cols-2">
        <CountList counts={result.created_counts} title="Created" />
        <CountList counts={result.skipped_counts} title="Cleared during reset" />
      </div>

      {result.warnings.length ? (
        <div className="space-y-2">
          <h5 className="text-sm font-semibold">Warnings</h5>
          {result.warnings.map((warning) => (
            <div className="rounded-md border border-amber-200 bg-amber-50 p-3 text-sm text-amber-900" key={warning}>{warning}</div>
          ))}
        </div>
      ) : null}

      {result.next_steps.length ? (
        <div className="space-y-2">
          <h5 className="text-sm font-semibold">Next steps</h5>
          <div className="grid gap-2 md:grid-cols-2">
            {result.next_steps.map((step) => (
              <div className="rounded-md border border-border p-3 text-sm" key={step}>{step}</div>
            ))}
          </div>
        </div>
      ) : null}

      {result.generated_vendor_links.length ? (
        <div className="space-y-3">
          <div>
            <h5 className="text-sm font-semibold">One-time vendor access</h5>
            <p className="mt-1 text-xs text-muted">Copy these tokens now. They will not be shown again after this result is dismissed.</p>
          </div>
          {result.generated_vendor_links.map((access) => <VendorTokenResult access={access} key={access.id} />)}
        </div>
      ) : null}
    </div>
  );
}

function CountList({ counts, title }: { counts: Record<string, number>; title: string }) {
  const entries = Object.entries(counts);
  return (
    <div className="rounded-md border border-border p-3">
      <h5 className="text-sm font-semibold">{title}</h5>
      {entries.length ? (
        <div className="mt-3 space-y-2">
          {entries.map(([key, value]) => (
            <div className="flex items-center justify-between gap-3 text-sm" key={key}>
              <span className="text-muted">{key.replaceAll("_", " ")}</span>
              <span className="font-semibold">{value}</span>
            </div>
          ))}
        </div>
      ) : (
        <p className="mt-2 text-sm text-muted">None</p>
      )}
    </div>
  );
}

function VendorTokenResult({ access }: { access: VendorAccessCreatedResponse }) {
  const value = access.access_url ?? access.access_token;
  return (
    <div className="rounded-md border border-border p-3">
      <div className="flex flex-col gap-3 lg:flex-row lg:items-start lg:justify-between">
        <div>
          <p className="font-medium">{access.vendor_name ?? access.email}</p>
          <p className="mt-1 text-xs text-muted">
            Token prefix {access.token_prefix ?? "hidden"} | {access.matching_invoice_count} matching invoice{access.matching_invoice_count === 1 ? "" : "s"}
          </p>
        </div>
        <Button
          onClick={() => {
            if (typeof navigator !== "undefined" && navigator.clipboard) {
              void navigator.clipboard.writeText(value);
            }
          }}
          size="sm"
          variant="secondary"
        >
          <Copy className="h-4 w-4" />
          Copy
        </Button>
      </div>
      <div className="mt-3 overflow-x-auto rounded-md bg-slate-950 px-3 py-2 font-mono text-xs text-slate-50">
        {value}
      </div>
    </div>
  );
}
